// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Wed Oct 09 10:37:29 2024

SignedMultiplier_ShiftAdd_4x4 SignedMultiplier_ShiftAdd_4x4_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.PLICAND(PLICAND_sig) ,	// input [3:0] PLICAND_sig
	.PLIER(PLIER_sig) ,	// input [3:0] PLIER_sig
	.DONE(DONE_sig) ,	// output  DONE_sig
	.PRODUCT(PRODUCT_sig) ,	// output [7:0] PRODUCT_sig
	.Q(Q_sig) ,	// output [3:0] Q_sig
	.M(M_sig) ,	// output [3:0] M_sig
	.A(A_sig) 	// output [4:0] A_sig
);

